# AI 프로그래밍 입문 - Week 3

---

### [실습 과제 (1/5)]

1. **Pandas 실습**: `Score`가 90점 이상인 사람들의 데이터만 추출하여 새로운 데이터프레임으로 저장하고 출력하세요. (R의 `subset`을 연상하며 해결)

In [ ]:
# 1. Pandas 실습 (위의 df 객체 활용)
# 여기에 코드를 작성하세요
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Futani'],
    'Age': [24, 27, 22, 32, 27],
    'Gender' : ['F','M', 'M', 'M', 'F'],
    'Score' : [90, 92, 89, 90, 89]
}
df = pd.DataFrame(data)

print("전체 데이터프레임:\n", df)

print("\n90점 이상 필터링 :\n", df[df['Score'] >= 90]) # 90점 이상만 추출

전체 데이터프레임:
       Name  Age Gender  Score
0    Alice   24      F     90
1      Bob   27      M     92
2  Charlie   22      M     89
3    David   32      M     90
4   Futani   27      F     89

90점 이상 필터링 :
     Name  Age Gender  Score
0  Alice   24      F     90
1    Bob   27      M     92
3  David   32      M     90


### [실습 과제 (2/5)]

2. **NumPy 실습**: 1부터 10까지의 숫자가 들어있는 NumPy 배열을 만들고, 모든 요소에 3을 곱한 결과를 브로드캐스팅을 활용해 출력하세요.

In [ ]:
# 2. NumPy 실습
# 여기에 코드를 작성하세요
import numpy as np

# 1 ~ 10까지 넘파이 배열 생성
n = []
for i in range(1, 11) :
    n.append(i)
numbers = np.array(n)
        
print('numbers : ', numbers)
print('\nshape : ', numbers.shape)

# 모든 요소에 3을 곱하기

print('\n모든 요소에 3을 곱한 결과(브로드캐스팅) : ', numbers*3)

numbers :  [ 1  2  3  4  5  6  7  8  9 10]

shape :  (10,)

모든 요소에 3을 곱한 결과(브로드캐스팅) :  [ 3  6  9 12 15 18 21 24 27 30]


### [실습 과제 (3/5)]

3. **JAX 실습 (선택)**: $g(x) = 3x^2 + 2x$ 함수를 정의하고 `jax.grad`를 사용하여 $x=2.0$일 때의 기울기를 구해보세요.

In [ ]:
# 3. JAX 실습 (선택, jax가 설치되어 있는 경우만)
# 여기에 코드를 작성하세요

import jax.numpy as jnp
from jax import grad

def g(x) :
    y = 3*x**2 + 2*x
    return y

# x=2 일때 함수 작동 테스트
print("g(2.0) = ", g(2.0))

# x=2 일때 기울기
dg = grad(g)
print("\ng'(2.0) = ", dg(2.0))

g(2.0) =  16.0

g'(2.0) =  14.0


### [실습 과제 (4/5)]

4. **Pseudo Inverse 실습**: 임의의 4x3 행렬을 만들고 유사 역행렬을 계산해보세요.

In [ ]:
# 4. Pseudo Inverse 실습
# 임의의 4x3 행렬을 만들고 유사 역행렬을 계산해보세요.
# 여기에 코드를 작성하세요
import numpy as np

# 4행 3열의 직사각형 행렬 A 정의
A = np.array([
    [1, 2, 3],
    [7, 8, 6],
    [5, 4, 3],
    [9, 7, 5],
])
print("원본 행렬 A (4x3) : \n", A)

# 유사 역행렬 계산
A_pinv = np.linalg.pinv(A)
print("\n유사 역행렬 A_pinv (3x4) : \n", A_pinv)

# 유사 역행렬 검증
I = np.dot(A_pinv, A)
print("\n A_pinv와 A의 내적(근사적인 단위행렬) : \n", np.round(I, 2))

원본 행렬 A (4x3) : 
 [[1 2 3]
 [7 8 6]
 [5 4 3]
 [9 7 5]]

유사 역행렬 A_pinv (3x4) : 
 [[ 0.0464135  -0.33333333  0.15611814  0.27848101]
 [-0.55485232  0.66666667 -0.22995781 -0.32911392]
 [ 0.68565401 -0.33333333  0.12447257  0.11392405]]

 A_pinv와 A의 내적(근사적인 단위행렬) : 
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]


### [실습 과제 (5/5)]

5. **SVD 실습**: NumPy의 np.random.rand()를 이용해 임의의 5x3 행렬 B를 만들고, np.linalg.svd(B)를 적용한 뒤 가장 큰 특이값(Singular Value)을 출력해보세요.

In [8]:
# 5. SVD 실습
# NumPy의 np.random.rand()를 이용해 임의의 5x3 행렬 B를 만들고,
# np.linalg.svd(B)를 적용한 뒤 가장 큰 특이값(Singular Value)을 출력해보세요.
# 여기에 코드를 작성하세요

import numpy as np

# np.random.rand()를 이용해 5x3 행렬 B 생성
np.random.seed(42)
B = np.random.rand(5, 3)
print("랜덤 행렬 B (5x3) : \n", B)

# 특이값 추출 및 가장 큰 특이값 출력
S = np.linalg.svd(B, compute_uv=False)
largest_S = S[0]
print("\n가장 큰 특이값 : \n", largest_S)

랜덤 행렬 B (5x3) : 
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]]

가장 큰 특이값 : 
 1.99063284799282
