# AI.Programming.101 - Week 3 실습
## 데이터 분석의 핵심: NumPy와 Pandas (그리고 R, JAX 비교)

이번 주에는 파이썬 데이터 분석의 필수 라이브러리인 **NumPy**와 **Pandas**의 기초 문법을 학습합니다.\n
또한 데이터 분석에서의 R 언어와의 차이점과 최신 AI 연산 도구인 JAX와의 차이점도 함께 비교합니다.

---

### 1. R 언어와 Python (Pandas) 비교

R 언어는 통계학자와 데이터 분석가를 위해 설계된 언어로 데이터프레임 구조를 언어 차원에서 기본적으로 지원합니다.\n
Python은 범용 언어이기 때문에 `pandas` 라이브러리를 통해 이 기능을 제공합니다.\n
아래는 R의 기본 `data.frame` 연산이 Pandas에서 어떻게 구현되는지 비교한 예시입니다.

In [2]:
import pandas as pd

# [R 언어 방식의 상상 코드]
# df <- data.frame(Name=c('Alice', 'Bob'), Age=c(24, 27))
# subset(df, Age > 25)

# [Python Pandas 방식]
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
}
df = pd.DataFrame(data)

print("전체 데이터프레임:\n", df)
print("\n25세 이상 필터링 (R의 subset 역할):\n", df[df['Age'] > 25])

전체 데이터프레임:
       Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
3    David   32

25세 이상 필터링 (R의 subset 역할):
     Name  Age
1    Bob   27
3  David   32


---

### 2. NumPy 기초

In [3]:
import numpy as np

# 1차원 배열 생성
arr1 = np.array([1, 2, 3, 4, 5])
print("1차원 배열:", arr1)
print("Shape:", arr1.shape)

# 2차원 배열 생성
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2차원 배열:\n", arr2)
print("Shape:", arr2.shape)

1차원 배열: [1 2 3 4 5]
Shape: (5,)

2차원 배열:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)


#### 2.1 기본 연산과 브로드캐스팅

In [4]:
# 배열 간의 연산 (Element-wise)
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print("a + b =", a + b)
print("a * b =", a * b)

# 브로드캐스팅: 스칼라값(단일 숫자)과의 연산도 자동으로 적용됩니다.
print("\na + 5 =", a + 5)

a + b = [11 22 33]
a * b = [10 40 90]

a + 5 = [15 25 35]


---

### 3. JAX vs NumPy
JAX는 고성능 머신러닝 연구를 위해 구글에서 개발한 라이브러리로, GPU/TPU 가속과 자동 미분(AutoGrad) 기능이 내장된 **'강력한 버전의 NumPy'** 입니다.
`jax.numpy`의 문법은 기존 `numpy`와 99% 일치하지만 더 강력합니다.

In [5]:
# 주의: 환경에 따라 jax 모듈이 설치되어 있어야 실행됩니다.
# !pip install jax jaxlib
try:
    import jax.numpy as jnp
    from jax import grad
    
    # JAX를 이용한 배열 생성 (문법이 numpy와 동일)
    j_arr = jnp.array([10., 20., 30.])
    print("JAX 배열 (DeviceArray):", j_arr)
    print("JAX 연산 (j_arr * 2) =", j_arr * 2)
    
    # 자동미분 맛보기: 함수 f(x) = x^2
    def f(x):
        return x**2
    
    # f(x)의 도함수 생성 (2x)
    df = grad(f)
    
    print("\nf(3.0) =", f(3.0))         # 9.0
    print("f'(3.0) [미분값] =", df(3.0)) # 6.0
    
except ImportError:
    print("현재 환경에 jax가 설치되어 있지 않습니다. `pip install jax jaxlib`을 통해 설치 후 실행해보세요.")

JAX 배열 (DeviceArray): [10. 20. 30.]
JAX 연산 (j_arr * 2) = [20. 40. 60.]

f(3.0) = 9.0
f'(3.0) [미분값] = 6.0


---

---
### 4. Python에서 R 함수 사용하기 (rpy2 라이브러리)

`rpy2` 라이브러리를 사용하면 Python 스크립트나 Jupyter Notebook 내에서 직접 R 코드를 실행하고 데이터를 주고받을 수 있습니다.\n
Jupyter Notebook에서는 `%%R` 매직 커맨드를 이용해 R 셀을 바로 사용할 수도 있습니다.

In [6]:
# 주의: 이 코드를 실행하려면 rpy2 라이브러리와 R이 시스템에 설치되어 있어야 합니다.
# !pip install rpy2
try:
    import rpy2.robjects as robjects
    from rpy2.robjects.packages import importr
    
    # R의 기본 내장 함수(base) 로드
    base = importr('base')
    
    # 파이썬에서 R의 sum 함수 호출 연습
    # R 코드: sum(c(1, 2, 3, 4, 5))
    r_vector = robjects.FloatVector([1.5, 2.5, 3.5])
    result = base.sum(r_vector)
    
    print("Python 배열을 R로 넘겨 sum() 함수를 돌린 결과:", result[0])
    
    # R 코드를 문자열로 직접 실행
    r_script = '''
    my_func <- function(x) {
        return(mean(x) + 10)
    }
    '''
    robjects.r(r_script)
    r_my_func = robjects.globalenv['my_func']
    print("\nR 스크립트로 정의한 my_func(c(10, 20)) 결과:", r_my_func(robjects.FloatVector([10, 20]))[0])
    
except ImportError:
    print("rpy2 모듈이 설치되어 있지 않습니다. pip install rpy2 를 통해 설치할 수 있습니다.")
except Exception as e:
    print("R이 제대로 동작하지 않습니다 (경로 확인 필요):", e)

Python 배열을 R로 넘겨 sum() 함수를 돌린 결과: 7.5

R 스크립트로 정의한 my_func(c(10, 20)) 결과: 25.0


Jupyter 노트북에서 **`%load_ext rpy2.ipython`** 을 실행한 후, **`%%R`** 매직 커맨드를 사용하면 아래와 같이 하나의 셀 전체를 R 환경처럼 사용할 수 있습니다.

In [ ]:
# %load_ext rpy2.ipython
## 아래 코드를 주석 해제 후 실행하면 R 환경에서 곧바로 코딩하는 것과 같이 동작합니다.
# %%R
# print("Hello from R!")
# data <- c(1, 2, 3, 4, 5)
# summary(data)

---
### 5. [심화] 고윳값(Eigenvalue)과 특이값 분해(SVD)

유사 역행렬(Pseudo Inverse)을 이해하기 위한 필수 뼈대 지식입니다.\n
데이터의 주요 축을 찾거나(PCA/Principal Component Analysis/ 차원 축소) 직사각형 행렬을 다루기 위해 **고윳값 분해(Eigendecomposition)**와 **특이값 분해(SVD)**를 학습합니다.

<<고윳값(Eigenvalue)과 고유벡터(eigenvector)가 어떻게 사용되나>>

1. 주성분 분석 (PCA, Principal Component Analysis)
데이터 과학과 통신 분야에서 가장 많이 쓰이는 사례입니다.

원리: 수많은 데이터가 흩어져 있을 때, 데이터의 분산(변화량)이 가장 큰 방향을 찾습니다. 이 방향이 바로 공분산 행렬의 고유벡터이며, 그 중요도가 고유값입니다.

용도: 차원 축소. 예를 들어 100개의 변수를 가진 복잡한 데이터를 정보 손실을 최소화하면서 2~3개로 줄여 시각화하거나 계산 속도를 높일 때 사용합니다.

2. 구글의 페이지랭크 (PageRank) 알고리즘
초기 구글을 만든 핵심 알고리즘입니다.

원리: 웹사이트들을 노드(점)로, 링크를 화살표로 연결한 거대한 행렬을 만듭니다. 이때 가장 중요한 페이지(권위 있는 페이지)를 찾는 과정이 이 행렬의 최대 고유값에 대응하는 고유벡터를 찾는 과정과 수학적으로 일치합니다.

용도: 검색 엔진에서 어떤 사이트를 상단에 보여줄지 결정하는 순위 산정.

3. 진동 분석 및 구조 공학
다리나 건물을 지을 때 붕괴 위험을 막기 위해 필수적입니다.

원리: 물리적 시스템의 강성과 질량을 행렬로 표현하면, 이 행렬의 **고유값은 '고유 진동수'**가 되고, **고유벡터는 '진동 모드(형태)'**가 됩니다.

용도: 외부 바람이나 지진의 진동수가 건물의 고유 진동수(고유값)와 일치하면 공진 현상으로 무너질 수 있는데, 이를 사전에 계산하여 설계에 반영합니다.

4. 컴퓨터 비전 및 이미지 처리
질문자님이 연구 중이신 **객체 탐지(YOLOv8)**나 이미지 인식의 기초 원리에도 들어있습니다.

고유얼굴(Eigenfaces): 사람의 얼굴 이미지들을 고유벡터로 분해하여 특징점만 추출하는 방식입니다. 초기 얼굴 인식 기술의 핵심이었습니다.

이미지 압축: 이미지 데이터 행렬에서 정보량이 적은 고유값 부분을 제거하여 용량을 줄이기도 합니다.

5. 양자 역학 (Quantum Mechanics)
원리: 양자역학에서 상태를 나타내는 연산자(행렬)의 고유값은 우리가 실제로 측정 가능한 물리량(에너지, 운동량 등)이 됩니다.

용도: 원자 수준의 물리 현상을 해석하는 기본 원리입니다.



<<특이값 분해(SVD, Singular Value Decomposition)>>

고유값 분해(Eigenvalue Decomposition)의 **'일반화된 버전'**
고유값 분해는 '정사각형 모양의 행렬(정방행렬)'에서만 가능하지만, **SVD는 가로세로 길이가 다른 어떤 모양의 행렬(직사각형 행렬)**에서도 사용할 수 있는 아주 강력한 도구입니다.

1. SVD의 수학적 정의임의의 $m \times n$ 행렬 $A$를 다음과 같이 세 개의 행렬의 곱으로 나누는 것을 말합니다.

"A = U＊Sigma＊V^T"

U(왼쪽 특이 벡터): 결과 공간에서의 회전 (차원 m X m)
//// Sigma(특이값): 각 축 방향으로의 확대/축소 크기 (차원 m X n, 대각 행렬). 이 값들이 큰 순서대로 정렬되어 있어 데이터의 중요도를 나타냅니다.
//// V^T(오른쪽 특이 벡터): 입력 공간에서의 회전 (차원 n X n)

2. SVD는 어디에 사용되나?

① 데이터 압축 및 차원 축소 (Truncated SVD)가장 대표적인 활용 사례입니다. 특이값(Sigma) 중에서 값이 큰 상위 몇 개만 남기고 나머지를 0으로 만들어 버리면, 데이터의 핵심 특징은 유지하면서 용량을 획기적으로 줄일 수 있습니다.
- 이미지 압축: 사진 행렬을 SVD로 분해해 작은 특이값들을 버리면, 눈으로는 차이를 느끼기 힘들지만 파일 용량은 매우 작아진 이미지를 얻을 수 있습니다.
- 노이즈 제거: 작은 특이값들은 대개 '노이즈(잡음)'에 해당하므로, 이를 제거하여 데이터의 순도를 높입니다.

② 추천 시스템 (Collaborative Filtering)넷플릭스나 유튜브의 추천 알고리즘 기초 모델입니다.원리: '사용자-영화' 평점 행렬은 빈칸(안 본 영화)이 아주 많은 거대한 행렬입니다. 이를 SVD로 분해하면 사용자의 취향(잠재 요인)과 영화의 특성을 파악할 수 있어, 보지 않은 영화의 평점을 예측할 수 있습니다.

③ 자연어 처리 (LSA, Latent Semantic Analysis)단어와 문서 사이의 관계를 파악하는 데 쓰입니다.수만 개의 단어가 포함된 문서 행렬을 SVD로 축소하면, 단어들 사이의 '숨겨진 의미(문맥)'를 찾아내어 비슷한 주제의 문서를 분류할 수 있습니다.

④ 의사 역행렬 (Pseudo-inverse) 계산수학적으로 역행렬이 존재하지 않는 행렬(직사각형 행렬 등)의 해를 구해야 할 때 SVD를 사용합니다. 이는 로봇 제어나 최적화 문제에서 시스템의 해를 찾을 때 필수적입니다.

In [23]:
import numpy as np

# -----------------------------------
# 1. 고윳값(Eigenvalue)과 고유벡터(Eigenvector)
# -----------------------------------
# (정방행렬 2x2)
A_sq = np.array([
    [4, 1],
    [2, 3]
])

print("=== 정방행렬 A_sq ===\n", A_sq)

# 고윳값(eigenvalues)과 고유벡터(eigenvectors) 계산
eigenvalues, eigenvectors = np.linalg.eig(A_sq)

print("\n고윳값 (Eigenvalues):", eigenvalues)
print("고유벡터 (Eigenvectors):\n", eigenvectors)

# 검증: A * v = lambda * v
v0 = eigenvectors[:, 0]    # 첫번째 고유벡터
lambda0 = eigenvalues[0]   # 첫번째 고윳값

print("\n검증 (A * v0):", np.dot(A_sq, v0))
print("검증 (lambda0 * v0):", lambda0 * v0)
print("(두 결과가 같으면 수학적으로 올바른 것입니다!)")

=== 정방행렬 A_sq ===
 [[4 1]
 [2 3]]

고윳값 (Eigenvalues): [5. 2.]
고유벡터 (Eigenvectors):
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]

검증 (A * v0): [3.53553391 3.53553391]
검증 (lambda0 * v0): [3.53553391 3.53553391]
(두 결과가 같으면 수학적으로 올바른 것입니다!)


In [24]:
# -----------------------------------
# 2. 특이값 분해 (Singular Value Decomposition, SVD)
# -----------------------------------
# (직사각형 행렬 3x2 - 앞선 데이터 예시)
A_rect = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print("=== 직사각형 행렬 A_rect (3x2) ===\n", A_rect)

# 특이값 분해 (A = U * Sigma * V^T)
# U: (3x3) 왼쪽 특이벡터 행렬
# S: (2,) 1차원 배열로 된 특이값 (Singular values)
# VT: (2x2) 오른쪽 특이벡터 행렬
U, S, VT = np.linalg.svd(A_rect)

print("\nU 행렬 (행 차원 회전):\n", U)
print("\n특이값 S (중요도/크기, 내림차순):", S) # S 데이터가 분산/정보량을 대변합니다
print("\nVT 행렬 (열 차원 회전):\n", VT)

=== 직사각형 행렬 A_rect (3x2) ===
 [[1 2]
 [3 4]
 [5 6]]

U 행렬 (행 차원 회전):
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

특이값 S (중요도/크기, 내림차순): [9.52551809 0.51430058]

VT 행렬 (열 차원 회전):
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


---
### 6. [심화] 유사 역행렬 (Pseudo Inverse)

정방행렬(N x N)이 아닌 행렬에 대해서도 역행렬과 비슷한 역할을 하는 행렬을 구하는 방법입니다.\n
머신러닝의 기초 알고리즘 중 평범한 '선형 회귀(Linear Regression)'의 최적 파라미터(가중치)를 오차 없이 단번에 계산할 때 사용됩니다.\n

NumPy에서는 `np.linalg.pinv(A)` 함수를 사용하여 구할 수 있습니다.

In [9]:
import numpy as np

# 1. 3행 2열의 직사각형 행렬 A (정방행렬이 아님)
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print("원본 행렬 A (3x2):\n", A)

# 2. 유사 역행렬 계산 (Moore-Penrose Pseudo Inverse)
A_pinv = np.linalg.pinv(A)

print("\n유사 역행렬 A_pinv (2x3):\n", A_pinv)

# 3. 유사 역행렬의 성질 확인 (A_pinv * A = I, 항등행렬)
# 완벽한 항등행렬이 나오는지 확인해봅시다. (소수점 아래 미세 오차 무시)
identity_approx = np.dot(A_pinv, A)
print("\nA_pinv와 A의 내적 (근사적인 단위행렬):\n", np.round(identity_approx, 2))

원본 행렬 A (3x2):
 [[1 2]
 [3 4]
 [5 6]]

유사 역행렬 A_pinv (2x3):
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]

A_pinv와 A의 내적 (근사적인 단위행렬):
 [[ 1.  0.]
 [-0.  1.]]


---
### 7. [실무 응용] SVD와 Pseudo Inverse를 활용한 GPS 위치 계산

우리가 매일 사용하는 스마트폰의 GPS는 위성(Satellite)으로부터 **위성의 현재 3차원 위치**와 **신호 송신 시간($t_i$)** 데이터를 받습니다.\n
수신기는 자신의 시계로 **수신 시간($t_{rec}$)**을 측정하여 위성과의 거리(Pseudo-range)를 계산하지만, 스마트폰의 시계는 부정확하기 때문에 **수신기 시계 오차(b)**가 미지수로 추가됩니다.\n

우리가 구해야 할 미지수는 4개($x, y, z, b$)인데, 상용 GPS는 6개 이상의 위성 신호를 잡습니다. 즉, 방정식이 미지수보다 많은 **초과 결정 시스템(Overdetermined System)**이 되므로 역행렬을 직접 구할 수 없습니다.\n
이 때 SVD를 이용한 **유사 역행렬(Pseudo Inverse)**로 가장 오차가 적은 최적의 위치(x, y, z)를 한 번에 계산해냅니다!

In [19]:
import numpy as np

# 빛의 속도 (km/s)
C = 299792.458 

# [1. 시뮬레이션 환경 구성]
# 6개 위성의 임의 3차원 좌표 (고도 약 20,000km 수준)
satellites = np.array([
    [15000, 12000, 20000],
    [-10000, 18000, 22000],
    [1000, -15000, 21000],
    [14000, -10000, 23000],
    [-12000, -8000, 24000],
    [-5000, 16000, 25000]
])

# 사용자의 실제 3차원 위치 (우리가 SVD 역산으로 찾아내야 할 정답)
true_pos = np.array([300, 400, 50])
true_clock_bias = 0.00001 # 수신기의 실제 시간 오차 (초 단위)

# (가상 생성) 위성이 신호를 보낸 시간 t_i 배열 생성
# 실제 거리 / 빛의 속도 = 도달에 걸린 순수 시간
transmit_times = []
receiver_time = 100.0 # 수신기가 신호를 받은 수신기 기준 시간(불안정함)

# 각 위성이 신호를 송신한 시간(t_i)을 역으로 시뮬레이션하여 쏜다고 가정
for sat in satellites:
    real_dist = np.linalg.norm(sat - true_pos)
    pure_travel_time = real_dist / C
    
    # 수신기가 100.0초에 받았다고 할때, 실제 세상 시간은 100.0 - 오차
    true_receiver_time = receiver_time - true_clock_bias
    t_i = true_receiver_time - pure_travel_time
    transmit_times.append(t_i)
transmit_times = np.array(transmit_times)

# --- 여기까지가 GPS 위성 시스템이 허공에 쏜 "숨겨진 정답" 입니다 ---

In [20]:
# [2. 수신기가 데이터를 받아서 Pseudo-range (의사 거리) 측정]
# 수신기는 위성 위치(satellites)와 송신 시간(transmit_times)을 전달받고, 자신의 수신 시간(receiver_time)을 뺍니다.

pseudo_ranges = []
for t_i in transmit_times:
    # P = c * (수신기 시계 시간 - 위성 송신 시간)
    # 이 거리 안에는 (실제 거리 + c*수신기 시간오차) 가 섞여 있습니다.
    noise = np.random.normal(0, 0.001) # 대기권 통과 전파 지연 등 약간의 노이즈
    P_i = C * (receiver_time - t_i) + noise 
    pseudo_ranges.append(P_i)
pseudo_ranges = np.array(pseudo_ranges)


In [21]:
# [3. 선형 방정식 A * x = b 세우기]
# 비선형 모델(구의 방정식)을 위성 1번 식을 뺌으로써 연립 일차 방정식(선형 모델)으로 변환
# 우리가 구할 미지수 배열 x_vec = [x, y, z, C*시계오차]
A = []
b = []

x1, y1, z1 = satellites[0]
P1 = pseudo_ranges[0]

for i in range(1, 6):
    xi, yi, zi = satellites[i]
    Pi = pseudo_ranges[i]
    
    # A 행렬: [ 2(Xi - X1), 2(Yi - Y1), 2(Zi - Z1), -2(Pi - P1) ]
    A_row = [
        2 * (xi - x1),
        2 * (yi - y1),
        2 * (zi - z1),
        -2 * (Pi - P1) # c*d 의 계수
    ]
    A.append(A_row)
    
    # b 벡터: Xi^2 - X1^2 + Yi^2 - Y1^2 + Zi^2 - Z1^2 - Pi^2 + P1^2
    b_val = (xi**2 - x1**2) + (yi**2 - y1**2) + (zi**2 - z1**2) - (Pi**2 - P1**2)
    b.append(b_val)

A = np.array(A) # 크기: 5 x 4
b = np.array(b) # 크기: 5


In [22]:
# [4. 유사 역행렬(Pseudo Inverse)로 해 구하기]
# A는 5x4의 직사각형 행렬이므로 역행렬(A^-1)이 없습니다.
# np.linalg.pinv(A) 를 통해 SVD 기반의 최적해를 도출합니다!
A_pinv = np.linalg.pinv(A)

# 행렬의 내적 연산 (A_pinv * b) 로 x_vec (x, y, z, c*d) 도출
calculated_vec = np.dot(A_pinv, b)

calculated_pos = calculated_vec[:3]
calculated_clock_bias = calculated_vec[3] / C # 오차 거리를 다시 시간(초)으로 복원

print("=== 실제 정답 위치 및 오차 ===")
print(f"X: {true_pos[0]:.2f}, Y: {true_pos[1]:.2f}, Z: {true_pos[2]:.2f}")
print(f"Clock Bias: {true_clock_bias:.6f} 초")

print("\n=== SVD 유사 역행렬로 역산출 한 결과 ===")
print(f"X: {calculated_pos[0]:.2f}, Y: {calculated_pos[1]:.2f}, Z: {calculated_pos[2]:.2f}")
print(f"Clock Bias: {calculated_clock_bias:.6f} 초")

print("\n[결론] 직사각형 행렬 시스템임에도 SVD 덕분에 오차를 최소화한 수신기의 정확한 좌표와 시간까지 알아냈습니다!")

=== 실제 정답 위치 및 오차 ===
X: 300.00, Y: 400.00, Z: 50.00
Clock Bias: 0.000010 초

=== SVD 유사 역행렬로 역산출 한 결과 ===
X: 300.00, Y: 400.00, Z: 50.00
Clock Bias: 0.000010 초

[결론] 직사각형 행렬 시스템임에도 SVD 덕분에 오차를 최소화한 수신기의 정확한 좌표와 시간까지 알아냈습니다!


### 8. 실습 과제 (Mission)

배운 개념을 활용하여 다음 과제를 수행하세요.

1. **Pandas 실습**: `Score`가 90점 이상인 사람들의 데이터만 추출하여 새로운 데이터프레임으로 저장하고 출력하세요. (R의 `subset`을 연상하며 해결)
2. **NumPy 실습**: 1부터 10까지의 숫자가 들어있는 NumPy 배열을 만들고, 모든 요소에 3을 곱한 결과를 브로드캐스팅을 활용해 출력하세요.
3. **JAX 실습 (선택)**: $g(x) = 3x^2 + 2x$ 함수를 정의하고 `jax.grad`를 사용하여 $x=2.0$일 때의 기울기를 구해보세요.

In [ ]:
# 1. Pandas 실습 (위의 df 객체 활용)
# 여기에 코드를 작성하세요


In [ ]:
# 2. NumPy 실습
# 여기에 코드를 작성하세요


In [ ]:
# 3. JAX 실습 (선택, jax가 설치되어 있는 경우만)
# 여기에 코드를 작성하세요


In [ ]:
# 4. Pseudo Inverse 실습
# 임의의 4x3 행렬을 만들고 유사 역행렬을 계산해보세요.
# 여기에 코드를 작성하세요


In [ ]:
# 5. SVD 실습
# NumPy의 np.random.rand()를 이용해 임의의 5x3 행렬 B를 만들고,
# np.linalg.svd(B)를 적용한 뒤 가장 큰 특이값(Singular Value)을 출력해보세요.
# 여기에 코드를 작성하세요
